import music from './assets/music/müzik.mp3'
export const MusicData=[
    {
        id:1,
        name:'Eminem',
        coverUrl:'https://pics.filmaffinity.com/Eminem_Without_Me_Music_Video-152736505-large.jpg',
        musicUrl:music
    },
    {
        id:2,
        name:'Eminem',
        coverUrl:'https://pics.filmaffinity.com/Eminem_Without_Me_Music_Video-152736505-large.jpg',
        musicUrl:music
    },
    {
        id:3,
        name:'Eminem',
        coverUrl:'https://pics.filmaffinity.com/Eminem_Without_Me_Music_Video-152736505-large.jpg',
        musicUrl:music
    },
    {
        id:4,
        name:'Eminem',
        coverUrl:'https://pics.filmaffinity.com/Eminem_Without_Me_Music_Video-152736505-large.jpg',
        musicUrl:music
    },
    {
        id:5,
        name:'Eminem',
        coverUrl:'https://pics.filmaffinity.com/Eminem_Without_Me_Music_Video-152736505-large.jpg',
        musicUrl:music
    },
    {
        id:6,
        name:'Eminem',
        coverUrl:'https://pics.filmaffinity.com/Eminem_Without_Me_Music_Video-152736505-large.jpg',
        musicUrl:music
    },
    {
        id:7,
        name:'Eminem',
        coverUrl:'https://pics.filmaffinity.com/Eminem_Without_Me_Music_Video-152736505-large.jpg',
        musicUrl:music
    },
    {
        id:8,
        name:'Eminem',
        coverUrl:'https://pics.filmaffinity.com/Eminem_Without_Me_Music_Video-152736505-large.jpg',
        musicUrl:music
    },
    {
        id:9,
        name:'Eminem',
        coverUrl:'https://pics.filmaffinity.com/Eminem_Without_Me_Music_Video-152736505-large.jpg',
        musicUrl:music
    },
    {
        id:10,
        name:'Eminem',
        coverUrl:'https://pics.filmaffinity.com/Eminem_Without_Me_Music_Video-152736505-large.jpg',
        musicUrl:music
    },
    {
        id:11,
        name:'Eminem',
        coverUrl:'https://pics.filmaffinity.com/Eminem_Without_Me_Music_Video-152736505-large.jpg',
        musicUrl:music
    },
];