import music from './assets/music/müzik.mp3'
export const MusicData=[
        {
          id:1,
          name:'Eminem',
          coverUrl:'https://pics.filmaffinity.com/Eminem_Without_Me_Music_Video-152736505-large.jpg',
          musicUrl:music
      },
      {
          id:2,
          name:'Eminem',
          coverUrl:'https://media.pitchfork.com/photos/5929bc61eb335119a49ecc59/1:1/w_600/62da6a2d.jpg',
          musicUrl:music
      },
      {
          id:3,
          name:'Eminem',
          coverUrl:'https://upload.wikimedia.org/wikipedia/tr/3/33/Eminem_Encore.jpg',
          musicUrl:music
      },
      {
          id:4,
          name:'Eminem',
          coverUrl:'https://m.media-amazon.com/images/I/71n0xmxpw7L._SL1400_.jpg',
          musicUrl:music
      },
      {
          id:5,
          name:'Eminem',
          coverUrl:'https://cdns-images.dzcdn.net/images/cover/716c2b9bebf9ba5282541a885d9b1e03/264x264.jpg',
          musicUrl:music
      },
      {
          id:6,
          name:'Eminem',
          coverUrl:'https://sticscrew.files.wordpress.com/2014/01/ceza.jpg',
          musicUrl:music
      },
      {
          id:7,
          name:'Eminem',
          coverUrl:'https://images.genius.com/dffecc3864078c4c54547169cfa521a8.1000x1000x1.jpg',
          musicUrl:music
      },
      {
          id:8,
          name:'Eminem',
          coverUrl:'https://i.pinimg.com/originals/ea/1f/64/ea1f64668a0af149a3277db9e9e54824.jpg',
          musicUrl:music
      },
      {
          id:9,
          name:'Eminem',
          coverUrl:'https://pics.filmaffinity.com/Eminem_Without_Me_Music_Video-152736505-large.jpg',
          musicUrl:music
      },
      {
          id:10,
          name:'Eminem',
          coverUrl:'https://pics.filmaffinity.com/Eminem_Without_Me_Music_Video-152736505-large.jpg',
          musicUrl:music
      },
      {
          id:11,
          name:'Eminem',
          coverUrl:'https://pics.filmaffinity.com/Eminem_Without_Me_Music_Video-152736505-large.jpg',
          musicUrl:music
      },
];